# region dubbo/connection.properties
com.dwarfeng.rbacds.dubbo.provider.group=${com.dwarfeng.essentials.dubbo.provider.rbacds.group}
# endregion
# region redis/prefix.properties
com.dwarfeng.rbacds.cache.prefix.entity.permission=${com.dwarfeng.essentials.cache.prefix.entity.rbacds.permission}
com.dwarfeng.rbacds.cache.prefix.entity.pexp=${com.dwarfeng.essentials.cache.prefix.entity.rbacds.pexp}
com.dwarfeng.rbacds.cache.prefix.entity.role=${com.dwarfeng.essentials.cache.prefix.entity.rbacds.role}
com.dwarfeng.rbacds.cache.prefix.entity.user=${com.dwarfeng.essentials.cache.prefix.entity.rbacds.user}
com.dwarfeng.rbacds.cache.prefix.entity.permission_group=\
  ${com.dwarfeng.essentials.cache.prefix.entity.rbacds.permission_group}
com.dwarfeng.rbacds.cache.prefix.entity.filter_support=${com.dwarfeng.essentials.cache.prefix.entity.rbacds.filter_support}
com.dwarfeng.rbacds.cache.prefix.entity.role_user_relation=\
  ${com.dwarfeng.essentials.cache.prefix.entity.rbacds.role_user_relation}
com.dwarfeng.rbacds.cache.prefix.entity.scope=${com.dwarfeng.essentials.cache.prefix.entity.rbacds.scope}
# endregion
# region redis/timeout.properties
com.dwarfeng.rbacds.cache.timeout.entity.user=${com.dwarfeng.essentials.cache.timeout.entity.rbacds.user}
com.dwarfeng.rbacds.cache.timeout.entity.role=${com.dwarfeng.essentials.cache.timeout.entity.rbacds.role}
com.dwarfeng.rbacds.cache.timeout.entity.pexp=${com.dwarfeng.essentials.cache.timeout.entity.rbacds.pexp}
com.dwarfeng.rbacds.cache.timeout.entity.permission=${com.dwarfeng.essentials.cache.timeout.entity.rbacds.permission}
com.dwarfeng.rbacds.cache.timeout.entity.permission_group=\
  ${com.dwarfeng.essentials.cache.timeout.entity.rbacds.permission_group}
com.dwarfeng.rbacds.cache.timeout.entity.permission_meta=\
  ${com.dwarfeng.essentials.cache.timeout.entity.rbacds.permission_meta}
com.dwarfeng.rbacds.cache.timeout.entity.filter_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.rbacds.filter_support}
com.dwarfeng.rbacds.cache.timeout.entity.role_user_relation=\
  ${com.dwarfeng.essentials.cache.timeout.entity.rbacds.role_user_relation}
com.dwarfeng.rbacds.cache.timeout.entity.scope=${com.dwarfeng.essentials.cache.timeout.entity.rbacds.scope}
# endregion
# region rbacds/launcher.properties
com.dwarfeng.rbacds.launcher.reset_filter_support=${com.dwarfeng.essentials.rbacds.launcher.reset_filter_support}
com.dwarfeng.rbacds.launcher.start_reset_delay=${com.dwarfeng.essentials.rbacds.launcher.start_reset_delay}
# endregion
# region rbacds/push.properties
com.dwarfeng.rbacds.pusher.type=${com.dwarfeng.essentials.rbacds.pusher.type}
com.dwarfeng.rbacds.pusher.multi.delegate_types=${com.dwarfeng.essentials.rbacds.pusher.multi.delegate_types}
com.dwarfeng.rbacds.pusher.log.log_level=${com.dwarfeng.essentials.rbacds.pusher.log.log_level}
# endregion
# region rbacds/reset.properties
com.dwarfeng.rbacds.resetter.fixed_delay.delay=${com.dwarfeng.essentials.rbacds.resetter.fixed_delay.delay}
com.dwarfeng.rbacds.resetter.fixed_rate.rate=${com.dwarfeng.essentials.rbacds.resetter.fixed_rate.rate}
com.dwarfeng.rbacds.resetter.cron.cron=${com.dwarfeng.essentials.rbacds.resetter.cron.cron}
# endregion
# region rbacds/local-cache.properties
com.dwarfeng.rbacds.local_cache.permission_user_analysis.ttl=\
  ${com.dwarfeng.essentials.rbacds.local_cache.permission_user_analysis.ttl}
com.dwarfeng.rbacds.local_cache.permission_user_analysis.cleanup_interval=\
  ${com.dwarfeng.essentials.rbacds.local_cache.permission_user_analysis.cleanup_interval}
com.dwarfeng.rbacds.local_cache.scoped_user_permission_analysis.ttl=\
  ${com.dwarfeng.essentials.rbacds.local_cache.scoped_user_permission_analysis.ttl}
com.dwarfeng.rbacds.local_cache.scoped_user_permission_analysis.cleanup_interval=\
  ${com.dwarfeng.essentials.rbacds.local_cache.scoped_user_permission_analysis.cleanup_interval}
com.dwarfeng.rbacds.local_cache.user_role_analysis.ttl=\
  ${com.dwarfeng.essentials.rbacds.local_cache.user_role_analysis.ttl}
com.dwarfeng.rbacds.local_cache.user_role_analysis.cleanup_interval=\
  ${com.dwarfeng.essentials.rbacds.local_cache.user_role_analysis.cleanup_interval}
# endregion
