# region dubbo/connection.properties
com.dwarfeng.voucher.dubbo.provider.group=${com.dwarfeng.essentials.dubbo.provider.voucher.group}
# endregion
# region redis/prefix.properties
com.dwarfeng.voucher.cache.prefix.entity.checker_info=\
  ${com.dwarfeng.essentials.cache.prefix.entity.voucher.checker_info}
com.dwarfeng.voucher.cache.prefix.entity.checker_support=\
  ${com.dwarfeng.essentials.cache.prefix.entity.voucher.checker_support}
com.dwarfeng.voucher.cache.prefix.entity.voucher=${com.dwarfeng.essentials.cache.prefix.entity.voucher.voucher}
com.dwarfeng.voucher.cache.prefix.entity.voucher_category=\
  ${com.dwarfeng.essentials.cache.prefix.entity.voucher.voucher_category}
com.dwarfeng.voucher.cache.prefix.entity.voucher_category_variable=\
  ${com.dwarfeng.essentials.cache.prefix.entity.voucher.voucher_category_variable}
com.dwarfeng.voucher.cache.prefix.entity.voucher_variable=\
  ${com.dwarfeng.essentials.cache.prefix.entity.voucher.voucher_variable}
# endregion
# region redis/timeout.properties
com.dwarfeng.voucher.cache.timeout.entity.checker_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.voucher.checker_info}
com.dwarfeng.voucher.cache.timeout.entity.checker_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.voucher.checker_support}
com.dwarfeng.voucher.cache.timeout.entity.voucher=${com.dwarfeng.essentials.cache.timeout.entity.voucher.voucher}
com.dwarfeng.voucher.cache.timeout.entity.voucher_category=\
  ${com.dwarfeng.essentials.cache.timeout.entity.voucher.voucher_category}
com.dwarfeng.voucher.cache.timeout.entity.voucher_category_variable=\
  ${com.dwarfeng.essentials.cache.timeout.entity.voucher.voucher_category_variable}
com.dwarfeng.voucher.cache.timeout.entity.voucher_variable=\
  ${com.dwarfeng.essentials.cache.timeout.entity.voucher.voucher_variable}
# endregion
# region voucher/cleanup.properties
com.dwarfeng.voucher.cleanup.cron=${com.dwarfeng.essentials.voucher.cleanup.cron}
# endregion
# region voucher/launcher.properties
com.dwarfeng.voucher.launcher.reset_checker_support=${com.dwarfeng.essentials.voucher.launcher.reset_checker_support}
com.dwarfeng.voucher.launcher.online_cleanup_delay=${com.dwarfeng.essentials.voucher.launcher.online_cleanup_delay}
com.dwarfeng.voucher.launcher.enable_cleanup_delay=${com.dwarfeng.essentials.voucher.launcher.enable_cleanup_delay}
com.dwarfeng.voucher.launcher.start_reset_delay=${com.dwarfeng.essentials.voucher.launcher.start_reset_delay}
# endregion
# region voucher/push.properties
com.dwarfeng.voucher.pusher.type=${com.dwarfeng.essentials.voucher.pusher.type}
com.dwarfeng.voucher.pusher.multi.delegate_types=${com.dwarfeng.essentials.voucher.pusher.multi.delegate_types}
com.dwarfeng.voucher.pusher.kafka.native.bootstrap_servers=\
  ${com.dwarfeng.essentials.voucher.pusher.kafka.native.bootstrap_servers}
com.dwarfeng.voucher.pusher.kafka.native.acks=${com.dwarfeng.essentials.voucher.pusher.kafka.native.acks}
com.dwarfeng.voucher.pusher.kafka.native.retries=${com.dwarfeng.essentials.voucher.pusher.kafka.native.retries}
com.dwarfeng.voucher.pusher.kafka.native.linger=${com.dwarfeng.essentials.voucher.pusher.kafka.native.linger}
com.dwarfeng.voucher.pusher.kafka.native.buffer_memory=\
  ${com.dwarfeng.essentials.voucher.pusher.kafka.native.buffer_memory}
com.dwarfeng.voucher.pusher.kafka.native.batch_size=${com.dwarfeng.essentials.voucher.pusher.kafka.native.batch_size}
com.dwarfeng.voucher.pusher.kafka.native.transaction_prefix=\
  ${com.dwarfeng.essentials.voucher.pusher.kafka.native.transaction_prefix}
com.dwarfeng.voucher.pusher.kafka.native.topic.check_reset=\
  ${com.dwarfeng.essentials.voucher.pusher.kafka.native.topic.check_reset}
com.dwarfeng.voucher.pusher.log.log_level=${com.dwarfeng.essentials.voucher.pusher.log.log_level}
# endregion
# region voucher/reset.properties
com.dwarfeng.voucher.resetter.fixed_delay.delay=${com.dwarfeng.essentials.voucher.resetter.fixed_delay.delay}
com.dwarfeng.voucher.resetter.fixed_rate.rate=${com.dwarfeng.essentials.voucher.resetter.fixed_rate.rate}
com.dwarfeng.voucher.resetter.cron.cron=${com.dwarfeng.essentials.voucher.resetter.cron.cron}
# endregion
