# region dubbo/connection.properties
com.dwarfeng.settingrepo.dubbo.provider.group=${dwarfeng.essentials.dubbo.provider.settingrepo.group}
# endregion
# region redis/prefix.properties
com.dwarfeng.settingrepo.cache.prefix.entity.formatter_support=
${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.formatter_support}=
com.dwarfeng.settingrepo.cache.prefix.entity.setting_category=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.setting_category}
com.dwarfeng.settingrepo.cache.prefix.entity.setting_node=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.setting_node}
com.dwarfeng.settingrepo.cache.prefix.entity.text_node=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.text_node}
com.dwarfeng.settingrepo.cache.prefix.entity.image_node=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.image_node}
com.dwarfeng.settingrepo.cache.prefix.entity.image_list_node=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.image_list_node}
com.dwarfeng.settingrepo.cache.prefix.entity.image_list_node_item=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.image_list_node_item}
com.dwarfeng.settingrepo.cache.prefix.entity.iahn_node=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.iahn_node}
com.dwarfeng.settingrepo.cache.prefix.entity.iahn_node_locale=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.iahn_node_locale}
com.dwarfeng.settingrepo.cache.prefix.entity.iahn_node_mek=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.iahn_node_mek}
com.dwarfeng.settingrepo.cache.prefix.entity.iahn_node_message=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.iahn_node_message}
com.dwarfeng.settingrepo.cache.prefix.entity.long_text_node=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.long_text_node}
com.dwarfeng.settingrepo.cache.prefix.entity.file_node=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.file_node}
com.dwarfeng.settingrepo.cache.prefix.entity.file_list_node=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.file_list_node}
com.dwarfeng.settingrepo.cache.prefix.entity.file_list_node_item=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.file_list_node_item}
com.dwarfeng.settingrepo.cache.prefix.entity.navigation_node=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.navigation_node}
com.dwarfeng.settingrepo.cache.prefix.entity.navigation_node_item=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.navigation_node_item}
com.dwarfeng.settingrepo.cache.prefix.entity.kv_node=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.kv_node}
com.dwarfeng.settingrepo.cache.prefix.entity.kv_node_item=\
  ${com.dwarfeng.essentials.cache.prefix.entity.settingrepo.kv_node_item}
# endregion
# region redis/timeout.properties
com.dwarfeng.settingrepo.cache.timeout.entity.formatter_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.formatter_support}
com.dwarfeng.settingrepo.cache.timeout.entity.setting_category=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.setting_category}
com.dwarfeng.settingrepo.cache.timeout.entity.setting_node=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.setting_node}
com.dwarfeng.settingrepo.cache.timeout.entity.text_node=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.text_node}
com.dwarfeng.settingrepo.cache.timeout.entity.image_node=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.image_node}
com.dwarfeng.settingrepo.cache.timeout.entity.image_list_node=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.image_list_node}
com.dwarfeng.settingrepo.cache.timeout.entity.image_list_node_item=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.image_list_node_item}
com.dwarfeng.settingrepo.cache.timeout.entity.iahn_node=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.iahn_node}
com.dwarfeng.settingrepo.cache.timeout.entity.iahn_node_locale=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.iahn_node_locale}
com.dwarfeng.settingrepo.cache.timeout.entity.iahn_node_mek=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.iahn_node_mek}
com.dwarfeng.settingrepo.cache.timeout.entity.iahn_node_message=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.iahn_node_message}
com.dwarfeng.settingrepo.cache.timeout.entity.long_text_node=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.long_text_node}
com.dwarfeng.settingrepo.cache.timeout.entity.file_node=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.file_node}
com.dwarfeng.settingrepo.cache.timeout.entity.file_list_node=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.file_list_node}
com.dwarfeng.settingrepo.cache.timeout.entity.file_list_node_item=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.file_list_node_item}
com.dwarfeng.settingrepo.cache.timeout.entity.navigation_node=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.navigation_node}
com.dwarfeng.settingrepo.cache.timeout.entity.navigation_node_item=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.navigation_node_item}
com.dwarfeng.settingrepo.cache.timeout.entity.kv_node=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.kv_node}
com.dwarfeng.settingrepo.cache.timeout.entity.kv_node_item=\
  ${com.dwarfeng.essentials.cache.timeout.entity.settingrepo.kv_node_item}
# endregion
# region settingrepo/iahn.properties
com.dwarfeng.settingrepo.iahn.cache.prefix.locale_map=\
  ${com.dwarfeng.essentials.settingrepo.iahn.cache.prefix.locale_map}
com.dwarfeng.settingrepo.iahn.cache.timeout.locale_map=\
  ${com.dwarfeng.essentials.settingrepo.iahn.cache.timeout.locale_map}
com.dwarfeng.settingrepo.iahn.cache.prefix.message_map=\
  ${com.dwarfeng.essentials.settingrepo.iahn.cache.prefix.message_map}
com.dwarfeng.settingrepo.iahn.cache.timeout.message_map=\
  ${com.dwarfeng.essentials.settingrepo.iahn.cache.timeout.message_map}
# endregion
# region settingrepo/image-thumbnail.properties
com.dwarfeng.settingrepo.image_thumbnail.width=${com.dwarfeng.essentials.settingrepo.image_thumbnail.width}
com.dwarfeng.settingrepo.image_thumbnail.height=${com.dwarfeng.essentials.settingrepo.image_thumbnail.height}
com.dwarfeng.settingrepo.image_thumbnail.quality=${com.dwarfeng.essentials.settingrepo.image_thumbnail.quality}
com.dwarfeng.settingrepo.image_thumbnail.output_format=\
  ${com.dwarfeng.essentials.settingrepo.image_thumbnail.output_format}
# endregion
# region settingrepo/launcher.properties
com.dwarfeng.settingrepo.launcher.reset_formatter_support=\
  ${com.dwarfeng.essentials.settingrepo.launcher.reset_formatter_support}
com.dwarfeng.settingrepo.launcher.start_reset_delay=${com.dwarfeng.essentials.settingrepo.launcher.start_reset_delay}
# endregion
# region settingrepo/navigation.properties
com.dwarfeng.settingrepo.navigation.cache.prefix.inspect_result=\
  ${com.dwarfeng.essentials.settingrepo.navigation.cache.prefix.inspect_result}
com.dwarfeng.settingrepo.navigation.cache.timeout.inspect_result=\
  ${com.dwarfeng.essentials.settingrepo.navigation.cache.timeout.inspect_result}
com.dwarfeng.settingrepo.navigation.format.start_index=\
  ${com.dwarfeng.essentials.settingrepo.navigation.format.start_index}
com.dwarfeng.settingrepo.navigation.format.index_step=\
  ${com.dwarfeng.essentials.settingrepo.navigation.format.index_step}
# endregion
# region settingrepo/push.properties
com.dwarfeng.settingrepo.pusher.type=${com.dwarfeng.essentials.settingrepo.pusher.type}
com.dwarfeng.settingrepo.pusher.multi.delegate_types=${com.dwarfeng.essentials.settingrepo.pusher.multi.delegate_types}
com.dwarfeng.settingrepo.pusher.log.log_level=${com.dwarfeng.essentials.settingrepo.pusher.log.log_level}
# endregion
# region settingrepo/reset.properties
com.dwarfeng.settingrepo.resetter.fixed_delay.delay=${com.dwarfeng.essentials.settingrepo.resetter.fixed_delay.delay}
com.dwarfeng.settingrepo.resetter.fixed_rate.rate=${com.dwarfeng.essentials.settingrepo.resetter.fixed_rate.rate}
com.dwarfeng.settingrepo.resetter.cron.cron=${com.dwarfeng.essentials.settingrepo.resetter.cron.cron}
com.dwarfeng.settingrepo.resetter.kafka.bootstrap_servers=\
  ${com.dwarfeng.essentials.settingrepo.resetter.kafka.bootstrap_servers}
com.dwarfeng.settingrepo.resetter.kafka.session_timeout_ms=\
  ${com.dwarfeng.essentials.settingrepo.resetter.kafka.session_timeout_ms}
com.dwarfeng.settingrepo.resetter.kafka.listener_id=\
  ${com.dwarfeng.essentials.settingrepo.resetter.kafka.listener_id}
com.dwarfeng.settingrepo.resetter.kafka.auto_offset_reset=\
  ${com.dwarfeng.essentials.settingrepo.resetter.kafka.auto_offset_reset}
com.dwarfeng.settingrepo.resetter.kafka.concurrency=\
  ${com.dwarfeng.essentials.settingrepo.resetter.kafka.concurrency}
com.dwarfeng.settingrepo.resetter.kafka.poll_timeout=\
  ${com.dwarfeng.essentials.settingrepo.resetter.kafka.poll_timeout}
com.dwarfeng.settingrepo.resetter.kafka.max_poll_records=\
  ${com.dwarfeng.essentials.settingrepo.resetter.kafka.max_poll_records}
com.dwarfeng.settingrepo.resetter.kafka.max_poll_interval_ms=\
  ${com.dwarfeng.essentials.settingrepo.resetter.kafka.max_poll_interval_ms}
com.dwarfeng.settingrepo.resetter.kafka.topic=${com.dwarfeng.essentials.settingrepo.resetter.kafka.topic}
# endregion
# region ftp/connection.properties
com.dwarfeng.settingrepo.ftp.host=${com.dwarfeng.essentials.ftp.host}
com.dwarfeng.settingrepo.ftp.port=${com.dwarfeng.essentials.ftp.port}
com.dwarfeng.settingrepo.ftp.username=${com.dwarfeng.essentials.ftp.username}
com.dwarfeng.settingrepo.ftp.password=${com.dwarfeng.essentials.ftp.password}
com.dwarfeng.settingrepo.ftp.server_charset=${com.dwarfeng.essentials.ftp.server_charset}
com.dwarfeng.settingrepo.ftp.connect_timeout=${com.dwarfeng.essentials.ftp.connect_timeout}
com.dwarfeng.settingrepo.ftp.noop_interval=${com.dwarfeng.essentials.ftp.noop_interval}
com.dwarfeng.settingrepo.ftp.buffer_size=${com.dwarfeng.essentials.ftp.buffer_size}
com.dwarfeng.settingrepo.ftp.temporary_file_directory_path=${com.dwarfeng.essentials.ftp.temporary_file_directory_path}
com.dwarfeng.settingrepo.ftp.temporary_file_prefix=${com.dwarfeng.essentials.ftp.temporary_file_prefix}
com.dwarfeng.settingrepo.ftp.temporary_file_suffix=${com.dwarfeng.essentials.ftp.temporary_file_suffix}
com.dwarfeng.settingrepo.ftp.file_copy_memory_buffer_size=${com.dwarfeng.essentials.ftp.file_copy_memory_buffer_size}
com.dwarfeng.settingrepo.ftp.data_connection_mode=${com.dwarfeng.essentials.ftp.data_connection_mode}
com.dwarfeng.settingrepo.ftp.data_timeout=${com.dwarfeng.essentials.ftp.data_timeout}
com.dwarfeng.settingrepo.ftp.active_remote_data_connection_mode_server_host=\
  ${com.dwarfeng.essentials.ftp.active_remote_data_connection_mode_server_host}
com.dwarfeng.settingrepo.ftp.active_remote_data_connection_mode_server_port=\
  ${com.dwarfeng.essentials.ftp.active_remote_data_connection_mode_server_port}
# endregion
# region ftp/path.properties
com.dwarfeng.settingrepo.ftp.root_path=${com.dwarfeng.essentials.ftp.root_path.settingrepo}
# endregion
