# region dubbo/connection.properties
com.dwarfeng.buddy.dubbo.provider.group=${dwarfeng.essentials.dubbo.provider.buddy.group}
# endregion
# region redis/prefix.properties
com.dwarfeng.buddy.cache.prefix.entity.avatar_info=${com.dwarfeng.essentials.cache.prefix.entity.buddy.avatar_info}
com.dwarfeng.buddy.cache.prefix.entity.notification=${com.dwarfeng.essentials.cache.prefix.entity.buddy.notification}
com.dwarfeng.buddy.cache.prefix.entity.profile=${com.dwarfeng.essentials.cache.prefix.entity.buddy.profile}
com.dwarfeng.buddy.cache.prefix.entity.user=${com.dwarfeng.essentials.cache.prefix.entity.buddy.user}
# endregion
# region redis/timeout.properties
com.dwarfeng.buddy.cache.timeout.entity.avatar_info=${com.dwarfeng.essentials.cache.timeout.entity.buddy.avatar_info}
com.dwarfeng.buddy.cache.timeout.entity.notification=${com.dwarfeng.essentials.cache.timeout.entity.buddy.notification}
com.dwarfeng.buddy.cache.timeout.entity.profile=${com.dwarfeng.essentials.cache.timeout.entity.buddy.profile}
com.dwarfeng.buddy.cache.timeout.entity.user=${com.dwarfeng.essentials.cache.timeout.entity.buddy.user}
# endregion
# region ftp/connection.properties
com.dwarfeng.buddy.ftp.host=${com.dwarfeng.essentials.ftp.host}
com.dwarfeng.buddy.ftp.port=${com.dwarfeng.essentials.ftp.port}
com.dwarfeng.buddy.ftp.username=${com.dwarfeng.essentials.ftp.username}
com.dwarfeng.buddy.ftp.password=${com.dwarfeng.essentials.ftp.password}
com.dwarfeng.buddy.ftp.server_charset=${com.dwarfeng.essentials.ftp.server_charset}
com.dwarfeng.buddy.ftp.connect_timeout=${com.dwarfeng.essentials.ftp.connect_timeout}
com.dwarfeng.buddy.ftp.noop_interval=${com.dwarfeng.essentials.ftp.noop_interval}
com.dwarfeng.buddy.ftp.buffer_size=${com.dwarfeng.essentials.ftp.buffer_size}
com.dwarfeng.buddy.ftp.temporary_file_directory_path=${com.dwarfeng.essentials.ftp.temporary_file_directory_path}
com.dwarfeng.buddy.ftp.temporary_file_prefix=${com.dwarfeng.essentials.ftp.temporary_file_prefix}
com.dwarfeng.buddy.ftp.temporary_file_suffix=${com.dwarfeng.essentials.ftp.temporary_file_suffix}
com.dwarfeng.buddy.ftp.file_copy_memory_buffer_size=${com.dwarfeng.essentials.ftp.file_copy_memory_buffer_size}
com.dwarfeng.buddy.ftp.data_connection_mode=${com.dwarfeng.essentials.ftp.data_connection_mode}
com.dwarfeng.buddy.ftp.data_timeout=${com.dwarfeng.essentials.ftp.data_timeout}
com.dwarfeng.buddy.ftp.active_remote_data_connection_mode_server_host=\
  ${com.dwarfeng.essentials.ftp.active_remote_data_connection_mode_server_host}
com.dwarfeng.buddy.ftp.active_remote_data_connection_mode_server_port=\
  ${com.dwarfeng.essentials.ftp.active_remote_data_connection_mode_server_port}
# endregion
# region ftp/path.properties
com.dwarfeng.buddy.ftp.root_path=${com.dwarfeng.essentials.ftp.root_path.buddy}
# endregion
