# region dubbo/connection.properties
com.dwarfeng.logicengine.dubbo.provider.group=${com.dwarfeng.essentials.dubbo.provider.logicengine.group}
# endregion
# region redis/prefix.properties
com.dwarfeng.logicengine.cache.prefix.entity.section=\
  ${com.dwarfeng.essentials.cache.prefix.entity.logicengine.section}
com.dwarfeng.logicengine.cache.prefix.entity.state=${com.dwarfeng.essentials.cache.prefix.entity.logicengine.state}
com.dwarfeng.logicengine.cache.prefix.entity.driver_info=\
  ${com.dwarfeng.essentials.cache.prefix.entity.logicengine.driver_info}
com.dwarfeng.logicengine.cache.prefix.entity.driver_support=\
  ${com.dwarfeng.essentials.cache.prefix.entity.logicengine.driver_support}
com.dwarfeng.logicengine.cache.prefix.entity.guarder_info=\
  ${com.dwarfeng.essentials.cache.prefix.entity.logicengine.guarder_info}
com.dwarfeng.logicengine.cache.prefix.entity.guarder_support=\
  ${com.dwarfeng.essentials.cache.prefix.entity.logicengine.guarder_support}
com.dwarfeng.logicengine.cache.prefix.entity.performer_info=\
  ${com.dwarfeng.essentials.cache.prefix.entity.logicengine.performer_info}
com.dwarfeng.logicengine.cache.prefix.entity.performer_support=\
  ${com.dwarfeng.essentials.cache.prefix.entity.logicengine.performer_support}
com.dwarfeng.logicengine.cache.prefix.entity.task=${com.dwarfeng.essentials.cache.prefix.entity.logicengine.task}
com.dwarfeng.logicengine.cache.prefix.entity.task_event=\
  ${com.dwarfeng.essentials.cache.prefix.entity.logicengine.task_event}
com.dwarfeng.logicengine.cache.prefix.entity.task_variable=\
  ${com.dwarfeng.essentials.cache.prefix.entity.logicengine.task_variable}
# endregion
# region redis/timeout.properties
com.dwarfeng.logicengine.cache.timeout.entity.section=\
  ${com.dwarfeng.essentials.cache.timeout.entity.logicengine.section}
com.dwarfeng.logicengine.cache.timeout.entity.state=${com.dwarfeng.essentials.cache.timeout.entity.logicengine.state}
com.dwarfeng.logicengine.cache.timeout.entity.driver_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.logicengine.driver_info}
com.dwarfeng.logicengine.cache.timeout.entity.driver_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.logicengine.driver_support}
com.dwarfeng.logicengine.cache.timeout.entity.guarder_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.logicengine.guarder_info}
com.dwarfeng.logicengine.cache.timeout.entity.guarder_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.logicengine.guarder_support}
com.dwarfeng.logicengine.cache.timeout.entity.performer_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.logicengine.performer_info}
com.dwarfeng.logicengine.cache.timeout.entity.performer_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.logicengine.performer_support}
com.dwarfeng.logicengine.cache.timeout.entity.task=${com.dwarfeng.essentials.cache.timeout.entity.logicengine.task}
com.dwarfeng.logicengine.cache.timeout.entity.task_event=\
  ${com.dwarfeng.essentials.cache.timeout.entity.logicengine.task_event}
com.dwarfeng.logicengine.cache.timeout.entity.task_variable=\
  ${com.dwarfeng.essentials.cache.timeout.entity.logicengine.task_variable}
# endregion
# region logic-engine/consume.properties
com.dwarfeng.logicengine.consume.threshold.warn=${com.dwarfeng.essentials.logicengine.consume.threshold.warn}
com.dwarfeng.logicengine.consume.consumer_thread=${com.dwarfeng.essentials.logicengine.consume.consumer_thread}
com.dwarfeng.logicengine.consume.buffer_size=${com.dwarfeng.essentials.logicengine.consume.buffer_size}
# endregion
# region logic-engine/dispatch.properties
com.dwarfeng.logicengine.dispatcher.type=${com.dwarfeng.essentials.logicengine.dispatcher.type}
com.dwarfeng.logicengine.dispatcher.kafka.bootstrap_servers=\
  ${com.dwarfeng.essentials.logicengine.dispatcher.kafka.bootstrap_servers}
com.dwarfeng.logicengine.dispatcher.kafka.acks=${com.dwarfeng.essentials.logicengine.dispatcher.kafka.acks}
com.dwarfeng.logicengine.dispatcher.kafka.retries=${com.dwarfeng.essentials.logicengine.dispatcher.kafka.retries}
com.dwarfeng.logicengine.dispatcher.kafka.linger=${com.dwarfeng.essentials.logicengine.dispatcher.kafka.linger}
com.dwarfeng.logicengine.dispatcher.kafka.buffer_memory=\
  ${com.dwarfeng.essentials.logicengine.dispatcher.kafka.buffer_memory}
com.dwarfeng.logicengine.dispatcher.kafka.batch_size=\
  ${com.dwarfeng.essentials.logicengine.dispatcher.kafka.batch_size}
com.dwarfeng.logicengine.dispatcher.kafka.transaction_prefix=\
  ${com.dwarfeng.essentials.logicengine.dispatcher.kafka.transaction_prefix}
com.dwarfeng.logicengine.dispatcher.kafka.load_balance_mode=\
  ${com.dwarfeng.essentials.logicengine.dispatcher.kafka.load_balance_mode}
com.dwarfeng.logicengine.dispatcher.kafka.partition_check_interval=\
  ${com.dwarfeng.essentials.logicengine.dispatcher.kafka.partition_check_interval}
com.dwarfeng.logicengine.dispatcher.kafka.topic.dispatch=\
  ${com.dwarfeng.essentials.logicengine.dispatcher.kafka.topic.dispatch}
# endregion
# region logic-engine/driver.properties
com.dwarfeng.logicengine.driver.kafka.dcti.bootstrap_servers=\
  ${com.dwarfeng.essentials.logicengine.driver.kafka.dcti.bootstrap_servers}
com.dwarfeng.logicengine.driver.kafka.dcti.session_timeout_ms=\
  ${com.dwarfeng.essentials.logicengine.driver.kafka.dcti.session_timeout_ms}
com.dwarfeng.logicengine.driver.kafka.dcti.auto_offset_reset=\
  ${com.dwarfeng.essentials.logicengine.driver.kafka.dcti.auto_offset_reset}
com.dwarfeng.logicengine.driver.kafka.dcti.concurrency=\
  ${com.dwarfeng.essentials.logicengine.driver.kafka.dcti.concurrency}
com.dwarfeng.logicengine.driver.kafka.dcti.poll_timeout=\
  ${com.dwarfeng.essentials.logicengine.driver.kafka.dcti.poll_timeout}
com.dwarfeng.logicengine.driver.kafka.dcti.listener_id=\
  ${com.dwarfeng.essentials.logicengine.driver.kafka.dcti.listener_id}
com.dwarfeng.logicengine.driver.kafka.dcti.listener_topic=\
  ${com.dwarfeng.essentials.logicengine.driver.kafka.dcti.listener_topic}
com.dwarfeng.logicengine.driver.kafka.dcti.max_poll_records=\
  ${com.dwarfeng.essentials.logicengine.driver.kafka.dcti.max_poll_records}
com.dwarfeng.logicengine.driver.kafka.dcti.max_poll_interval_ms=\
  ${com.dwarfeng.essentials.logicengine.driver.kafka.dcti.max_poll_interval_ms}
# endregion
# region logic-engine/launcher.properties
com.dwarfeng.logicengine.launcher.reset_performer_support=\
  ${com.dwarfeng.essentials.logicengine.launcher.reset_performer_support}
com.dwarfeng.logicengine.launcher.reset_guarder_support=\
  ${com.dwarfeng.essentials.logicengine.launcher.reset_guarder_support}
com.dwarfeng.logicengine.launcher.reset_driver_support=\
  ${com.dwarfeng.essentials.logicengine.launcher.reset_driver_support}
com.dwarfeng.logicengine.launcher.online_task_check_delay=\
  ${com.dwarfeng.essentials.logicengine.launcher.online_task_check_delay}
com.dwarfeng.logicengine.launcher.enable_task_check_delay=\
  ${com.dwarfeng.essentials.logicengine.launcher.enable_task_check_delay}
com.dwarfeng.logicengine.launcher.start_receive_delay=\
  ${com.dwarfeng.essentials.logicengine.launcher.start_receive_delay}
com.dwarfeng.logicengine.launcher.online_supervise_delay=\
  ${com.dwarfeng.essentials.logicengine.launcher.online_supervise_delay}
com.dwarfeng.logicengine.launcher.enable_supervise_delay=\
  ${com.dwarfeng.essentials.logicengine.launcher.enable_supervise_delay}
com.dwarfeng.logicengine.launcher.online_purge_delay=\
  ${com.dwarfeng.essentials.logicengine.launcher.online_purge_delay}
com.dwarfeng.logicengine.launcher.enable_purge_delay=\
  ${com.dwarfeng.essentials.logicengine.launcher.enable_purge_delay}
com.dwarfeng.logicengine.launcher.start_reset_delay=${com.dwarfeng.essentials.logicengine.launcher.start_reset_delay}
# endregion
# region logic-engine/purge.properties
com.dwarfeng.logicengine.purge.retention_duration=${com.dwarfeng.essentials.logicengine.purge.retention_duration}
com.dwarfeng.logicengine.purge.task_cron=${com.dwarfeng.essentials.logicengine.purge.task_cron}
com.dwarfeng.logicengine.purge.max_page_size=${com.dwarfeng.essentials.logicengine.purge.max_page_size}
com.dwarfeng.logicengine.purge.max_deletion_size=${com.dwarfeng.essentials.logicengine.purge.max_deletion_size}
# endregion
# region logic-engine/push.properties
com.dwarfeng.logicengine.pusher.type=${com.dwarfeng.essentials.logicengine.pusher.type}
com.dwarfeng.logicengine.pusher.multi.delegate_types=\
  ${com.dwarfeng.essentials.logicengine.pusher.multi.delegate_types}
com.dwarfeng.logicengine.pusher.kafka.native.bootstrap_servers=\
  ${com.dwarfeng.essentials.logicengine.pusher.kafka.native.bootstrap_servers}
com.dwarfeng.logicengine.pusher.kafka.native.acks=${com.dwarfeng.essentials.logicengine.pusher.kafka.native.acks}
com.dwarfeng.logicengine.pusher.kafka.native.retries=\
  ${com.dwarfeng.essentials.logicengine.pusher.kafka.native.retries}
com.dwarfeng.logicengine.pusher.kafka.native.linger=${com.dwarfeng.essentials.logicengine.pusher.kafka.native.linger}
com.dwarfeng.logicengine.pusher.kafka.native.buffer_memory=\
  ${com.dwarfeng.essentials.logicengine.pusher.kafka.native.buffer_memory}
com.dwarfeng.logicengine.pusher.kafka.native.batch_size=\
  ${com.dwarfeng.essentials.logicengine.pusher.kafka.native.batch_size}
com.dwarfeng.logicengine.pusher.kafka.native.transaction_prefix=\
  ${com.dwarfeng.essentials.logicengine.pusher.kafka.native.transaction_prefix}
com.dwarfeng.logicengine.pusher.kafka.native.topic.task_finished=\
  ${com.dwarfeng.essentials.logicengine.pusher.kafka.native.topic.task_finished}
com.dwarfeng.logicengine.pusher.kafka.native.topic.task_failed=\
  ${com.dwarfeng.essentials.logicengine.pusher.kafka.native.topic.task_failed}
com.dwarfeng.logicengine.pusher.kafka.native.topic.task_expired=\
  ${com.dwarfeng.essentials.logicengine.pusher.kafka.native.topic.task_expired}
com.dwarfeng.logicengine.pusher.kafka.native.topic.task_died=\
  ${com.dwarfeng.essentials.logicengine.pusher.kafka.native.topic.task_died}
com.dwarfeng.logicengine.pusher.kafka.native.topic.supervise_reset=\
  ${com.dwarfeng.essentials.logicengine.pusher.kafka.native.topic.supervise_reset}
com.dwarfeng.logicengine.pusher.kafka.native.topic.job_reset=\
  ${com.dwarfeng.essentials.logicengine.pusher.kafka.native.topic.job_reset}
com.dwarfeng.logicengine.pusher.kafka.native.topic.purge_finished=\
  ${com.dwarfeng.essentials.logicengine.pusher.kafka.native.topic.purge_finished}
com.dwarfeng.logicengine.pusher.kafka.native.topic.purge_failed=\
  ${com.dwarfeng.essentials.logicengine.pusher.kafka.native.topic.purge_failed}
com.dwarfeng.logicengine.pusher.log.log_level=${com.dwarfeng.essentials.logicengine.pusher.log.log_level}
# endregion
# region logic-engine/receive.properties
com.dwarfeng.logicengine.receiver.type=${com.dwarfeng.essentials.logicengine.receiver.type}
com.dwarfeng.logicengine.receiver.kafka.bootstrap_servers=\
  ${com.dwarfeng.essentials.logicengine.receiver.kafka.bootstrap_servers}
com.dwarfeng.logicengine.receiver.kafka.session_timeout_ms=\
  ${com.dwarfeng.essentials.logicengine.receiver.kafka.session_timeout_ms}
com.dwarfeng.logicengine.receiver.kafka.auto_offset_reset=\
  ${com.dwarfeng.essentials.logicengine.receiver.kafka.auto_offset_reset}
com.dwarfeng.logicengine.receiver.kafka.concurrency=${com.dwarfeng.essentials.logicengine.receiver.kafka.concurrency}
com.dwarfeng.logicengine.receiver.kafka.poll_timeout=\
  ${com.dwarfeng.essentials.logicengine.receiver.kafka.poll_timeout}
com.dwarfeng.logicengine.receiver.kafka.listener_id=${com.dwarfeng.essentials.logicengine.receiver.kafka.listener_id}
com.dwarfeng.logicengine.receiver.kafka.listener_topic=\
  ${com.dwarfeng.essentials.logicengine.receiver.kafka.listener_topic}
com.dwarfeng.logicengine.receiver.kafka.max_poll_records=\
  ${com.dwarfeng.essentials.logicengine.receiver.kafka.max_poll_records}
com.dwarfeng.logicengine.receiver.kafka.max_poll_interval_ms=\
  ${com.dwarfeng.essentials.logicengine.receiver.kafka.max_poll_interval_ms}
# endregion
# region logic-engine/reset.properties
com.dwarfeng.logicengine.resetter.fixed_delay.delay=${com.dwarfeng.essentials.logicengine.resetter.fixed_delay.delay}
com.dwarfeng.logicengine.resetter.fixed_rate.rate=${com.dwarfeng.essentials.logicengine.resetter.fixed_rate.rate}
com.dwarfeng.logicengine.resetter.cron.cron=${com.dwarfeng.essentials.logicengine.resetter.cron.cron}
# endregion
# region logic-engine/task.properties
com.dwarfeng.logicengine.task.die_timeout=${com.dwarfeng.essentials.logicengine.task.die_timeout}
com.dwarfeng.logicengine.task.beat_interval=${com.dwarfeng.essentials.logicengine.task.beat_interval}
com.dwarfeng.logicengine.task.check.expire_check.cron=\
  ${com.dwarfeng.essentials.logicengine.task.check.expire_check.cron}
com.dwarfeng.logicengine.task.check.die_check.cron=${com.dwarfeng.essentials.logicengine.task.check.die_check.cron}
# endregion
