# region dubbo/connection.properties
com.dwarfeng.fileio.dubbo.provider.group=${com.dwarfeng.essentials.dubbo.provider.fileio.group}
# endregion
# region redis/prefix.properties
com.dwarfeng.fileio.cache.prefix.entity.export_conf=${com.dwarfeng.essentials.cache.prefix.entity.fileio.export_conf}
com.dwarfeng.fileio.cache.prefix.entity.exporter_info=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.exporter_info}
com.dwarfeng.fileio.cache.prefix.entity.exporter_support=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.exporter_support}
com.dwarfeng.fileio.cache.prefix.entity.export_file_info=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.export_file_info}
com.dwarfeng.fileio.cache.prefix.entity.export_task=${com.dwarfeng.essentials.cache.prefix.entity.fileio.export_task}
com.dwarfeng.fileio.cache.prefix.entity.export_task_setting=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.export_task_setting}
com.dwarfeng.fileio.cache.prefix.entity.export_template_info=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.export_template_info}
com.dwarfeng.fileio.cache.prefix.entity.import_conf=${com.dwarfeng.essentials.cache.prefix.entity.fileio.import_conf}
com.dwarfeng.fileio.cache.prefix.entity.importer_info=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.importer_info}
com.dwarfeng.fileio.cache.prefix.entity.importer_support=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.importer_support}
com.dwarfeng.fileio.cache.prefix.entity.import_file_info=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.import_file_info}
com.dwarfeng.fileio.cache.prefix.entity.import_task=${com.dwarfeng.essentials.cache.prefix.entity.fileio.import_task}
com.dwarfeng.fileio.cache.prefix.entity.import_task_setting=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.import_task_setting}
com.dwarfeng.fileio.cache.prefix.entity.import_template_info=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.import_template_info}
com.dwarfeng.fileio.cache.prefix.entity.reader_info=${com.dwarfeng.essentials.cache.prefix.entity.fileio.reader_info}
com.dwarfeng.fileio.cache.prefix.entity.reader_support=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.reader_support}
com.dwarfeng.fileio.cache.prefix.entity.writer_info=${com.dwarfeng.essentials.cache.prefix.entity.fileio.writer_info}
com.dwarfeng.fileio.cache.prefix.entity.writer_support=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.writer_support}
com.dwarfeng.fileio.cache.prefix.entity.export_metadata=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.export_metadata}
com.dwarfeng.fileio.cache.prefix.entity.import_metadata=\
  ${com.dwarfeng.essentials.cache.prefix.entity.fileio.import_metadata}
com.dwarfeng.fileio.cache.prefix.entity.user=${com.dwarfeng.essentials.cache.prefix.entity.fileio.user}
# endregion
# region redis/timeout.properties
com.dwarfeng.fileio.cache.timeout.entity.export_conf=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.export_conf}
com.dwarfeng.fileio.cache.timeout.entity.exporter_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.exporter_info}
com.dwarfeng.fileio.cache.timeout.entity.exporter_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.exporter_support}
com.dwarfeng.fileio.cache.timeout.entity.export_file_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.export_file_info}
com.dwarfeng.fileio.cache.timeout.entity.export_task=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.export_task}
com.dwarfeng.fileio.cache.timeout.entity.export_task_setting=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.export_task_setting}
com.dwarfeng.fileio.cache.timeout.entity.export_template_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.export_template_info}
com.dwarfeng.fileio.cache.timeout.entity.import_conf=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.import_conf}
com.dwarfeng.fileio.cache.timeout.entity.importer_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.importer_info}
com.dwarfeng.fileio.cache.timeout.entity.importer_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.importer_support}
com.dwarfeng.fileio.cache.timeout.entity.import_file_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.import_file_info}
com.dwarfeng.fileio.cache.timeout.entity.import_task=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.import_task}
com.dwarfeng.fileio.cache.timeout.entity.import_task_setting=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.import_task_setting}
com.dwarfeng.fileio.cache.timeout.entity.import_template_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.import_template_info}
com.dwarfeng.fileio.cache.timeout.entity.reader_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.reader_info}
com.dwarfeng.fileio.cache.timeout.entity.reader_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.reader_support}
com.dwarfeng.fileio.cache.timeout.entity.writer_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.writer_info}
com.dwarfeng.fileio.cache.timeout.entity.writer_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.writer_support}
com.dwarfeng.fileio.cache.timeout.entity.export_metadata=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.export_metadata}
com.dwarfeng.fileio.cache.timeout.entity.import_metadata=\
  ${com.dwarfeng.essentials.cache.timeout.entity.fileio.import_metadata}
com.dwarfeng.fileio.cache.timeout.entity.user=${com.dwarfeng.essentials.cache.timeout.entity.fileio.user}
# endregion
# region fileio/launcher.properties
com.dwarfeng.fileio.launcher.reset_exporter_support=${com.dwarfeng.essentials.fileio.launcher.reset_exporter_support}
com.dwarfeng.fileio.launcher.reset_importer_support=${com.dwarfeng.essentials.fileio.launcher.reset_importer_support}
com.dwarfeng.fileio.launcher.reset_reader_support=${com.dwarfeng.essentials.fileio.launcher.reset_reader_support}
com.dwarfeng.fileio.launcher.reset_writer_support=${com.dwarfeng.essentials.fileio.launcher.reset_writer_support}
com.dwarfeng.fileio.launcher.start_reset_delay=${com.dwarfeng.essentials.fileio.launcher.start_reset_delay}
com.dwarfeng.fileio.launcher.online_task_check_delay=\
  ${com.dwarfeng.essentials.fileio.launcher.online_task_check_delay}
com.dwarfeng.fileio.launcher.enable_task_check_delay=\
  ${com.dwarfeng.essentials.fileio.launcher.enable_task_check_delay}
com.dwarfeng.fileio.launcher.online_purge_delay=${com.dwarfeng.essentials.fileio.launcher.online_purge_delay}
com.dwarfeng.fileio.launcher.enable_purge_delay=${com.dwarfeng.essentials.fileio.launcher.enable_purge_delay}
# endregion
# region fileio/purge.properties
com.dwarfeng.fileio.purge.retention_duration=${com.dwarfeng.essentials.fileio.purge.retention_duration}
com.dwarfeng.fileio.purge.task_cron=${com.dwarfeng.essentials.fileio.purge.task_cron}
com.dwarfeng.fileio.purge.max_page_size=${com.dwarfeng.essentials.fileio.purge.max_page_size}
com.dwarfeng.fileio.purge.max_deletion_size=${com.dwarfeng.essentials.fileio.purge.max_deletion_size}
# endregion
# region fileio/push.properties
com.dwarfeng.fileio.pusher.type=${com.dwarfeng.essentials.fileio.pusher.type}
com.dwarfeng.fileio.pusher.multi.delegate_types=${com.dwarfeng.essentials.fileio.pusher.multi.delegate_types}
com.dwarfeng.fileio.pusher.kafka.native.bootstrap_servers=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.bootstrap_servers}
com.dwarfeng.fileio.pusher.kafka.native.acks=${com.dwarfeng.essentials.fileio.pusher.kafka.native.acks}
com.dwarfeng.fileio.pusher.kafka.native.retries=${com.dwarfeng.essentials.fileio.pusher.kafka.native.retries}
com.dwarfeng.fileio.pusher.kafka.native.linger=${com.dwarfeng.essentials.fileio.pusher.kafka.native.linger}
com.dwarfeng.fileio.pusher.kafka.native.buffer_memory=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.buffer_memory}
com.dwarfeng.fileio.pusher.kafka.native.batch_size=${com.dwarfeng.essentials.fileio.pusher.kafka.native.batch_size}
com.dwarfeng.fileio.pusher.kafka.native.transaction_prefix=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.transaction_prefix}
com.dwarfeng.fileio.pusher.kafka.native.topic.export_reset=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.topic.export_reset}
com.dwarfeng.fileio.pusher.kafka.native.topic.import_reset=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.topic.import_reset}
com.dwarfeng.fileio.pusher.kafka.native.topic.export_task_finished=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.topic.export_task_finished}
com.dwarfeng.fileio.pusher.kafka.native.topic.export_task_failed=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.topic.export_task_failed}
com.dwarfeng.fileio.pusher.kafka.native.topic.export_task_expired=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.topic.export_task_expired}
com.dwarfeng.fileio.pusher.kafka.native.topic.export_task_dead=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.topic.export_task_dead}
com.dwarfeng.fileio.pusher.kafka.native.topic.import_task_finished=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.topic.import_task_finished}
com.dwarfeng.fileio.pusher.kafka.native.topic.import_task_failed=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.topic.import_task_failed}
com.dwarfeng.fileio.pusher.kafka.native.topic.import_task_expired=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.topic.import_task_expired}
com.dwarfeng.fileio.pusher.kafka.native.topic.import_task_dead=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.topic.import_task_dead}
com.dwarfeng.fileio.pusher.kafka.native.topic.purge_finished=\
  ${com.dwarfeng.essentials.fileio.pusher.kafka.native.topic.purge_finished}
com.dwarfeng.fileio.pusher.log.log_level=${com.dwarfeng.essentials.fileio.pusher.log.log_level}
# endregion
# region fileio/read.properties
com.dwarfeng.fileio.reader.spls.args_resolver.fastjson.auto_type_accepts=\
  ${com.dwarfeng.essentials.fileio.reader.spls.args_resolver.fastjson.auto_type_accepts}
# endregion
# region fileio/reset.properties
com.dwarfeng.fileio.resetter.fixed_delay.delay=${com.dwarfeng.essentials.fileio.resetter.fixed_delay.delay}
com.dwarfeng.fileio.resetter.fixed_rate.rate=${com.dwarfeng.essentials.fileio.resetter.fixed_rate.rate}
com.dwarfeng.fileio.resetter.cron.cron=${com.dwarfeng.essentials.fileio.resetter.cron.cron}
# endregion
# region fileio/task.properties
com.dwarfeng.fileio.task.export.expire_timeout=${com.dwarfeng.essentials.fileio.task.export.expire_timeout}
com.dwarfeng.fileio.task.export.dead_timeout=${com.dwarfeng.essentials.fileio.task.export.dead_timeout}
com.dwarfeng.fileio.task.export.beat_interval=${com.dwarfeng.essentials.fileio.task.export.beat_interval}
com.dwarfeng.fileio.task.import.expire_timeout=${com.dwarfeng.essentials.fileio.task.import.expire_timeout}
com.dwarfeng.fileio.task.import.dead_timeout=${com.dwarfeng.essentials.fileio.task.import.dead_timeout}
com.dwarfeng.fileio.task.import.beat_interval=${com.dwarfeng.essentials.fileio.task.import.beat_interval}
com.dwarfeng.fileio.task.check.expire_check.cron=${com.dwarfeng.essentials.fileio.task.check.expire_check.cron}
com.dwarfeng.fileio.task.check.dead_check.cron=${com.dwarfeng.essentials.fileio.task.check.dead_check.cron}
# endregion
# region tmpstg/settings.properties
com.dwarfeng.fileio.tmpstg.temporary_file_directory_path=\
  ${com.dwarfeng.essentials.fileio.tmpstg.temporary_file_directory_path}
com.dwarfeng.fileio.tmpstg.temporary_file_prefix=${com.dwarfeng.essentials.fileio.tmpstg.temporary_file_prefix}
com.dwarfeng.fileio.tmpstg.temporary_file_suffix=${com.dwarfeng.essentials.fileio.tmpstg.temporary_file_suffix}
com.dwarfeng.fileio.tmpstg.max_buffer_size_per_storage=\
  ${com.dwarfeng.essentials.fileio.tmpstg.max_buffer_size_per_storage}
com.dwarfeng.fileio.tmpstg.max_buffer_size_total=${com.dwarfeng.essentials.fileio.tmpstg.max_buffer_size_total}
com.dwarfeng.fileio.tmpstg.clear_disposed_interval=${com.dwarfeng.essentials.fileio.tmpstg.clear_disposed_interval}
com.dwarfeng.fileio.tmpstg.check_memory_interval=${com.dwarfeng.essentials.fileio.tmpstg.check_memory_interval}
# endregion
# region ftp/connection.properties
com.dwarfeng.fileio.ftp.host=${com.dwarfeng.essentials.ftp.host}
com.dwarfeng.fileio.ftp.port=${com.dwarfeng.essentials.ftp.port}
com.dwarfeng.fileio.ftp.username=${com.dwarfeng.essentials.ftp.username}
com.dwarfeng.fileio.ftp.password=${com.dwarfeng.essentials.ftp.password}
com.dwarfeng.fileio.ftp.server_charset=${com.dwarfeng.essentials.ftp.server_charset}
com.dwarfeng.fileio.ftp.connect_timeout=${com.dwarfeng.essentials.ftp.connect_timeout}
com.dwarfeng.fileio.ftp.noop_interval=${com.dwarfeng.essentials.ftp.noop_interval}
com.dwarfeng.fileio.ftp.buffer_size=${com.dwarfeng.essentials.ftp.buffer_size}
com.dwarfeng.fileio.ftp.temporary_file_directory_path=${com.dwarfeng.essentials.ftp.temporary_file_directory_path}
com.dwarfeng.fileio.ftp.temporary_file_prefix=${com.dwarfeng.essentials.ftp.temporary_file_prefix}
com.dwarfeng.fileio.ftp.temporary_file_suffix=${com.dwarfeng.essentials.ftp.temporary_file_suffix}
com.dwarfeng.fileio.ftp.file_copy_memory_buffer_size=${com.dwarfeng.essentials.ftp.file_copy_memory_buffer_size}
com.dwarfeng.fileio.ftp.data_connection_mode=${com.dwarfeng.essentials.ftp.data_connection_mode}
com.dwarfeng.fileio.ftp.data_timeout=${com.dwarfeng.essentials.ftp.data_timeout}
com.dwarfeng.fileio.ftp.active_remote_data_connection_mode_server_host=\
  ${com.dwarfeng.essentials.ftp.active_remote_data_connection_mode_server_host}
com.dwarfeng.fileio.ftp.active_remote_data_connection_mode_server_port=\
  ${com.dwarfeng.essentials.ftp.active_remote_data_connection_mode_server_port}
# endregion
# region ftp/path.properties
com.dwarfeng.fileio.ftp.root_path=${com.dwarfeng.essentials.ftp.root_path.fileio}
# endregion
