# region dubbo/connection.properties
com.dwarfeng.notify.dubbo.provider.group=${com.dwarfeng.essentials.dubbo.provider.notify.group}
# endregion
# region redis/prefix.properties
com.dwarfeng.notify.cache.prefix.entity.user=${com.dwarfeng.essentials.cache.prefix.entity.notify.user}
com.dwarfeng.notify.cache.prefix.entity.router_info=${com.dwarfeng.essentials.cache.prefix.entity.notify.router_info}
com.dwarfeng.notify.cache.prefix.entity.router_support=\
  ${com.dwarfeng.essentials.cache.prefix.entity.notify.router_support}
com.dwarfeng.notify.cache.prefix.entity.notify_setting=\
  ${com.dwarfeng.essentials.cache.prefix.entity.notify.notify_setting}
com.dwarfeng.notify.cache.prefix.entity.sender_info=${com.dwarfeng.essentials.cache.prefix.entity.notify.sender_info}
com.dwarfeng.notify.cache.prefix.entity.sender_support=\
  ${com.dwarfeng.essentials.cache.prefix.entity.notify.sender_support}
com.dwarfeng.notify.cache.prefix.entity.topic=${com.dwarfeng.essentials.cache.prefix.entity.notify.topic}
com.dwarfeng.notify.cache.prefix.entity.dispatcher_info=\
  ${com.dwarfeng.essentials.cache.prefix.entity.notify.dispatcher_info}
com.dwarfeng.notify.cache.prefix.entity.dispatcher_support=\
  ${com.dwarfeng.essentials.cache.prefix.entity.notify.dispatcher_support}
com.dwarfeng.notify.cache.prefix.entity.meta=${com.dwarfeng.essentials.cache.prefix.entity.notify.meta}
com.dwarfeng.notify.cache.prefix.entity.meta_indicator=\
  ${com.dwarfeng.essentials.cache.prefix.entity.notify.meta_indicator}
com.dwarfeng.notify.cache.prefix.entity.notify_history=\
  ${com.dwarfeng.essentials.cache.prefix.entity.notify.notify_history}
com.dwarfeng.notify.cache.prefix.entity.notify_info_record=\
  ${com.dwarfeng.essentials.cache.prefix.entity.notify.notify_info_record}
com.dwarfeng.notify.cache.prefix.entity.notify_send_record=\
  ${com.dwarfeng.essentials.cache.prefix.entity.notify.notify_send_record}
# endregion
# region redis/timeout.properties
com.dwarfeng.notify.cache.timeout.entity.user=${com.dwarfeng.essentials.cache.timeout.entity.notify.user}
com.dwarfeng.notify.cache.timeout.entity.router_info=${com.dwarfeng.essentials.cache.timeout.entity.notify.router_info}
com.dwarfeng.notify.cache.timeout.entity.router_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.notify.router_support}
com.dwarfeng.notify.cache.timeout.entity.notify_setting=\
  ${com.dwarfeng.essentials.cache.timeout.entity.notify.notify_setting}
com.dwarfeng.notify.cache.timeout.entity.sender_info=${com.dwarfeng.essentials.cache.timeout.entity.notify.sender_info}
com.dwarfeng.notify.cache.timeout.entity.sender_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.notify.sender_support}
com.dwarfeng.notify.cache.timeout.entity.topic=${com.dwarfeng.essentials.cache.timeout.entity.notify.topic}
com.dwarfeng.notify.cache.timeout.entity.dispatcher_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.notify.dispatcher_info}
com.dwarfeng.notify.cache.timeout.entity.dispatcher_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.notify.dispatcher_support}
com.dwarfeng.notify.cache.timeout.entity.meta=${com.dwarfeng.essentials.cache.timeout.entity.notify.meta}
com.dwarfeng.notify.cache.timeout.entity.meta_indicator=\
  ${com.dwarfeng.essentials.cache.timeout.entity.notify.meta_indicator}
com.dwarfeng.notify.cache.timeout.entity.notify_history=\
  ${com.dwarfeng.essentials.cache.timeout.entity.notify.notify_history}
com.dwarfeng.notify.cache.timeout.entity.notify_info_record=\
  ${com.dwarfeng.essentials.cache.timeout.entity.notify.notify_info_record}
com.dwarfeng.notify.cache.timeout.entity.notify_send_record=\
  ${com.dwarfeng.essentials.cache.timeout.entity.notify.notify_send_record}
# endregion
# region notify/launcher.properties
com.dwarfeng.notify.launcher.reset_router_support=${com.dwarfeng.essentials.notify.launcher.reset_router_support}
com.dwarfeng.notify.launcher.reset_sender_support=${com.dwarfeng.essentials.notify.launcher.reset_sender_support}
com.dwarfeng.notify.launcher.reset_dispatcher_support=\
  ${com.dwarfeng.essentials.notify.launcher.reset_dispatcher_support}
com.dwarfeng.notify.launcher.start_reset_delay=${com.dwarfeng.essentials.notify.launcher.start_reset_delay}
com.dwarfeng.notify.launcher.online_purge_delay=${com.dwarfeng.essentials.notify.launcher.online_purge_delay}
com.dwarfeng.notify.launcher.enable_purge_delay=${com.dwarfeng.essentials.notify.launcher.enable_purge_delay}
# endregion
# region notify/purge.properties
com.dwarfeng.notify.purge.retention_duration=${com.dwarfeng.essentials.notify.purge.retention_duration}
com.dwarfeng.notify.purge.task_cron=${com.dwarfeng.essentials.notify.purge.task_cron}
com.dwarfeng.notify.purge.max_page_size=${com.dwarfeng.essentials.notify.purge.max_page_size}
com.dwarfeng.notify.purge.max_deletion_size=${com.dwarfeng.essentials.notify.purge.max_deletion_size}
# endregion
# region notify/push.properties
com.dwarfeng.notify.pusher.type=${com.dwarfeng.essentials.notify.pusher.type}
com.dwarfeng.notify.pusher.multi.delegate_types=${com.dwarfeng.essentials.notify.pusher.multi.delegate_types}
com.dwarfeng.notify.pusher.log.log_level=${com.dwarfeng.essentials.notify.pusher.log.log_level}
# endregion
# region notify/reset.properties
com.dwarfeng.notify.resetter.fixed_delay.delay=${com.dwarfeng.essentials.notify.resetter.fixed_delay.delay}
com.dwarfeng.notify.resetter.fixed_rate.rate=${com.dwarfeng.essentials.notify.resetter.fixed_rate.rate}
com.dwarfeng.notify.resetter.cron.cron=${com.dwarfeng.essentials.notify.resetter.cron.cron}
com.dwarfeng.notify.resetter.kafka.bootstrap_servers=${com.dwarfeng.essentials.notify.resetter.kafka.bootstrap_servers}
com.dwarfeng.notify.resetter.kafka.session_timeout_ms=\
  ${com.dwarfeng.essentials.notify.resetter.kafka.session_timeout_ms}
com.dwarfeng.notify.resetter.kafka.listener_id=${com.dwarfeng.essentials.notify.resetter.kafka.listener_id}
com.dwarfeng.notify.resetter.kafka.auto_offset_reset=${com.dwarfeng.essentials.notify.resetter.kafka.auto_offset_reset}
com.dwarfeng.notify.resetter.kafka.concurrency=${com.dwarfeng.essentials.notify.resetter.kafka.concurrency}
com.dwarfeng.notify.resetter.kafka.poll_timeout=${com.dwarfeng.essentials.notify.resetter.kafka.poll_timeout}
com.dwarfeng.notify.resetter.kafka.max_poll_records=${com.dwarfeng.essentials.notify.resetter.kafka.max_poll_records}
com.dwarfeng.notify.resetter.kafka.max_poll_interval_ms=\
  ${com.dwarfeng.essentials.notify.resetter.kafka.max_poll_interval_ms}
com.dwarfeng.notify.resetter.kafka.topic=${com.dwarfeng.essentials.notify.resetter.kafka.topic}
# endregion
