# region dubbo/connection.properties
com.dwarfeng.acckeeper.dubbo.provider.group=${com.dwarfeng.essentials.dubbo.provider.acckeeper.group}
# endregion
# region redis/prefix.properties
com.dwarfeng.acckeeper.cache.prefix.entity.account=${com.dwarfeng.essentials.cache.prefix.entity.acckeeper.account}
com.dwarfeng.acckeeper.cache.prefix.entity.login_state=\
  ${com.dwarfeng.essentials.cache.prefix.entity.acckeeper.login_state}
com.dwarfeng.acckeeper.cache.prefix.entity.login_history=\
  ${com.dwarfeng.essentials.cache.prefix.entity.acckeeper.login_history}
com.dwarfeng.acckeeper.cache.prefix.entity.protector_info=\
  ${com.dwarfeng.essentials.cache.prefix.entity.acckeeper.protector_info}
com.dwarfeng.acckeeper.cache.prefix.entity.protector_support=\
  ${com.dwarfeng.essentials.cache.prefix.entity.acckeeper.protector_support}
com.dwarfeng.acckeeper.cache.prefix.entity.protector_variable=\
  ${com.dwarfeng.essentials.cache.prefix.entity.acckeeper.protector_variable}
com.dwarfeng.acckeeper.cache.prefix.entity.login_param_record=\
  ${com.dwarfeng.essentials.cache.prefix.entity.acckeeper.login_param_record}
com.dwarfeng.acckeeper.cache.prefix.entity.protect_detail_record=\
  ${com.dwarfeng.essentials.cache.prefix.entity.acckeeper.protect_detail_record}
com.dwarfeng.acckeeper.cache.prefix.entity.derive_history=\
  ${com.dwarfeng.essentials.cache.prefix.entity.acckeeper.derive_history}
# endregion
# region redis/timeout.properties
com.dwarfeng.acckeeper.cache.timeout.entity.account=${com.dwarfeng.essentials.cache.timeout.entity.acckeeper.account}
com.dwarfeng.acckeeper.cache.timeout.entity.login_state=\
  ${com.dwarfeng.essentials.cache.timeout.entity.acckeeper.login_state}
com.dwarfeng.acckeeper.cache.timeout.entity.login_history=\
  ${com.dwarfeng.essentials.cache.timeout.entity.acckeeper.login_history}
com.dwarfeng.acckeeper.cache.timeout.entity.protector_info=\
  ${com.dwarfeng.essentials.cache.timeout.entity.acckeeper.protector_info}
com.dwarfeng.acckeeper.cache.timeout.entity.protector_support=\
  ${com.dwarfeng.essentials.cache.timeout.entity.acckeeper.protector_support}
com.dwarfeng.acckeeper.cache.timeout.entity.protector_variable=\
  ${com.dwarfeng.essentials.cache.timeout.entity.acckeeper.protector_variable}
com.dwarfeng.acckeeper.cache.timeout.entity.login_param_record=\
  ${com.dwarfeng.essentials.cache.timeout.entity.acckeeper.login_param_record}
com.dwarfeng.acckeeper.cache.timeout.entity.protect_detail_record=\
  ${com.dwarfeng.essentials.cache.timeout.entity.acckeeper.protect_detail_record}
com.dwarfeng.acckeeper.cache.timeout.entity.derive_history=\
  ${com.dwarfeng.essentials.cache.timeout.entity.acckeeper.derive_history}
# endregion
# region acckeeper/clean.properties
com.dwarfeng.acckeeper.clean.expired_login_state.cron=\
  ${com.dwarfeng.essentials.acckeeper.clean.expired_login_state.cron}
# endregion
# region acckeeper/derive.properties
com.dwarfeng.acckeeper.acckeeper.derive.dynamic.expire_duration=\
  ${com.dwarfeng.essentials.acckeeper.acckeeper.derive.dynamic.expire_duration}
# endregion
# region acckeeper/login.properties
com.dwarfeng.acckeeper.acckeeper.login.dynamic.expire_duration=\
  ${com.dwarfeng.essentials.acckeeper.acckeeper.login.dynamic.expire_duration}
# endregion
# region acckeeper/launcher.properties
com.dwarfeng.acckeeper.launcher.reset_protector_support=\
  ${com.dwarfeng.essentials.acckeeper.launcher.reset_protector_support}
com.dwarfeng.acckeeper.launcher.online_clean_delay=${com.dwarfeng.essentials.acckeeper.launcher.online_clean_delay}
com.dwarfeng.acckeeper.launcher.enable_clean_delay=${com.dwarfeng.essentials.acckeeper.launcher.enable_clean_delay}
com.dwarfeng.acckeeper.launcher.start_reset_delay=${com.dwarfeng.essentials.acckeeper.launcher.start_reset_delay}
com.dwarfeng.acckeeper.launcher.online_purge_delay=${com.dwarfeng.essentials.acckeeper.launcher.online_purge_delay}
com.dwarfeng.acckeeper.launcher.enable_purge_delay=${com.dwarfeng.essentials.acckeeper.launcher.enable_purge_delay}
# endregion
# region acckeeper/lskgen.properties
com.dwarfeng.acckeeper.lskgen.type=${com.dwarfeng.essentials.acckeeper.lskgen.type}
com.dwarfeng.acckeeper.lskgen.randx.length=${com.dwarfeng.essentials.acckeeper.lskgen.randx.length}
# endregion
# region acckeeper/purge.properties
com.dwarfeng.acckeeper.purge.retention_duration=${com.dwarfeng.essentials.acckeeper.purge.retention_duration}
com.dwarfeng.acckeeper.purge.task_cron=${com.dwarfeng.essentials.acckeeper.purge.task_cron}
com.dwarfeng.acckeeper.purge.max_page_size=${com.dwarfeng.essentials.acckeeper.purge.max_page_size}
com.dwarfeng.acckeeper.purge.max_deletion_size=${com.dwarfeng.essentials.acckeeper.purge.max_deletion_size}
# endregion
# region acckeeper/push.properties
com.dwarfeng.acckeeper.pusher.type=${com.dwarfeng.essentials.acckeeper.pusher.type}
com.dwarfeng.acckeeper.pusher.multi.delegate_types=${com.dwarfeng.essentials.acckeeper.pusher.multi.delegate_types}
com.dwarfeng.acckeeper.pusher.log.log_level=${com.dwarfeng.essentials.acckeeper.pusher.log.log_level}
# endregion
# region acckeeper/register.properties
com.dwarfeng.acckeeper.register.password.salt_log_rounds=\
  ${com.dwarfeng.essentials.acckeeper.register.password.salt_log_rounds}
com.dwarfeng.acckeeper.register.default_protector.type=\
  ${com.dwarfeng.essentials.acckeeper.register.default_protector.type}
com.dwarfeng.acckeeper.register.default_protector.param=\
  ${com.dwarfeng.essentials.acckeeper.register.default_protector.param}
# endregion
# region acckeeper/reset.properties
com.dwarfeng.acckeeper.resetter.fixed_delay.delay=${com.dwarfeng.essentials.acckeeper.resetter.fixed_delay.delay}
com.dwarfeng.acckeeper.resetter.fixed_rate.rate=${com.dwarfeng.essentials.acckeeper.resetter.fixed_rate.rate}
com.dwarfeng.acckeeper.resetter.cron.cron=${com.dwarfeng.essentials.acckeeper.resetter.cron.cron}
# endregion
