#------------------------------------------------------------------------------------
#  \u7F13\u5B58\u65F6\u5B9E\u4F53\u7684\u952E\u7684\u683C\u5F0F
#------------------------------------------------------------------------------------
# \u683C\u5F0F\u5316\u5668\u652F\u6301\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.formatter_support=\
  com.dwarfeng.settingrepo.entity.formatter_support.
# \u8BBE\u7F6E\u7C7B\u522B\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.setting_category=\
  com.dwarfeng.settingrepo.entity.setting_category.
# \u8BBE\u7F6E\u8282\u70B9\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.setting_node=com.dwarfeng.settingrepo.entity.setting_node.
# \u6587\u672C\u8282\u70B9\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.text_node=com.dwarfeng.settingrepo.entity.text_node.
# \u56FE\u7247\u8282\u70B9\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.image_node=com.dwarfeng.settingrepo.entity.image_node.
# \u56FE\u7247\u5217\u8868\u8282\u70B9\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.image_list_node=com.dwarfeng.settingrepo.entity.image_list_node.
# \u56FE\u7247\u5217\u8868\u8282\u70B9\u6761\u76EE\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.image_list_node_item=\
  com.dwarfeng.settingrepo.entity.image_list_node_item.
# \u56FD\u9645\u5316\u8282\u70B9\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.iahn_node=com.dwarfeng.settingrepo.entity.iahn_node.
# \u56FD\u9645\u5316\u8282\u70B9\u6761\u76EE\u5730\u533A\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.iahn_node_locale=\
  com.dwarfeng.settingrepo.entity.iahn_node_locale.
# \u56FD\u9645\u5316\u8282\u70B9\u6761\u76EE Mek \u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.iahn_node_mek=com.dwarfeng.settingrepo.entity.iahn_node_mek.
# \u56FD\u9645\u5316\u8282\u70B9\u6761\u76EE Message \u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.iahn_node_message=\
  com.dwarfeng.settingrepo.entity.iahn_node_message.
# \u957F\u6587\u672C\u8282\u70B9\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.long_text_node=com.dwarfeng.settingrepo.entity.long_text_node.
# \u6587\u4EF6\u8282\u70B9\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.file_node=com.dwarfeng.settingrepo.entity.file_node.
# \u6587\u4EF6\u5217\u8868\u8282\u70B9\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.file_list_node=com.dwarfeng.settingrepo.entity.file_list_node.
# \u6587\u4EF6\u5217\u8868\u9879\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.file_list_node_item=\
  com.dwarfeng.settingrepo.entity.file_list_node_item.
# \u5BFC\u822A\u8282\u70B9\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.navigation_node=com.dwarfeng.settingrepo.entity.navigation_node.
# \u5BFC\u822A\u8282\u70B9\u6761\u76EE\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.navigation_node_item=\
  com.dwarfeng.settingrepo.entity.navigation_node_item.
# \u952E\u503C\u5BF9\u8282\u70B9\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.kv_node=com.dwarfeng.settingrepo.entity.kv_node.
# \u952E\u503C\u5BF9\u8282\u70B9\u6761\u76EE\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.settingrepo.kv_node_item=com.dwarfeng.settingrepo.entity.kv_node_item.
