#------------------------------------------------------------------------------------
#  \u7F13\u5B58\u65F6\u5B9E\u4F53\u7684\u952E\u7684\u683C\u5F0F
#------------------------------------------------------------------------------------
# \u7528\u6237\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.acckeeper.account=com.dwarfeng.acckeeper.entity.account.
# \u767B\u5F55\u72B6\u6001\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.acckeeper.login_state=com.dwarfeng.acckeeper.entity.login_state.
# \u767B\u5F55\u5386\u53F2\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.acckeeper.login_history=com.dwarfeng.acckeeper.entity.login_history.
# \u4FDD\u62A4\u5668\u4FE1\u606F\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.acckeeper.protector_info=com.dwarfeng.acckeeper.entity.protector_info.
# \u4FDD\u62A4\u5668\u652F\u6301\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.acckeeper.protector_support=com.dwarfeng.acckeeper.entity.protector_support.
# \u4FDD\u62A4\u5668\u53D8\u91CF\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.acckeeper.protector_variable=\
  com.dwarfeng.acckeeper.entity.protector_variable.
# \u767B\u5F55\u53C2\u6570\u8BB0\u5F55\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.acckeeper.login_param_record=\
  com.dwarfeng.acckeeper.entity.login_param_record.
# \u4FDD\u62A4\u8BE6\u7EC6\u4FE1\u606F\u8BB0\u5F55\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.acckeeper.protect_detail_record=\
  com.dwarfeng.acckeeper.entity.protect_detail_record.
# \u6D3E\u751F\u5386\u53F2\u5BF9\u8C61\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.acckeeper.derive_history=com.dwarfeng.acckeeper.entity.derive_history.
