###################################################
#                      spls                       #
###################################################
# Subgrade PresetLookupService \u8BFB\u53D6\u5668\u7684 fastjson \u503C\u89E3\u6790\u5668 autoType \u7684\u767D\u540D\u5355\u3002
com.dwarfeng.essentials.fileio.reader.spls.args_resolver.fastjson.auto_type_accepts=\
  com.dwarfeng.subgrade.stack.bean.key.ByteIdKey,com.dwarfeng.subgrade.stack.bean.key.DenseUuidKey,com.dwarfeng.subgrade.stack.bean.key.IntegerIdKey,com.dwarfeng.subgrade.stack.bean.key.LongIdKey,com.dwarfeng.subgrade.stack.bean.key.StringIdKey,com.dwarfeng.subgrade.stack.bean.key.UuidKey
