<?xml version="1.0" encoding="UTF-8"?>

<project
        xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
        http://maven.apache.org/xsd/maven-4.0.0.xsd"
>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.dwarfeng</groupId>
        <artifactId>dwarfeng-essentials</artifactId>
        <version>1.0.0.a</version>
    </parent>

    <artifactId>dwarfeng-essentials-impl</artifactId>
    <name>dwarfeng-essentials-impl</name>
    <url>http://maven.apache.org</url>

    <dependencies>
        <!-- Subgrade 组件 -->
        <dependency>
            <groupId>com.dwarfeng</groupId>
            <artifactId>subgrade-impl</artifactId>
        </dependency>
        <!-- Spring-telqos 组件 -->
        <dependency>
            <groupId>com.dwarfeng</groupId>
            <artifactId>spring-telqos-core</artifactId>
        </dependency>
        <!-- Spring-terminator 组件 -->
        <dependency>
            <groupId>com.dwarfeng</groupId>
            <artifactId>spring-terminator-core</artifactId>
        </dependency>
        <!-- Dwarfeng-datamark 组件 -->
        <dependency>
            <groupId>com.dwarfeng</groupId>
            <artifactId>dwarfeng-datamark-core</artifactId>
        </dependency>
        <!-- Dwarfeng-ftp 组件 -->
        <dependency>
            <groupId>com.dwarfeng</groupId>
            <artifactId>dwarfeng-ftp-core</artifactId>
        </dependency>
        <!-- SnowFlake 服务 -->
        <dependency>
            <groupId>com.dwarfeng</groupId>
            <artifactId>snowflake-distributed-service-api</artifactId>
        </dependency>
        <!-- Account-keeper 服务 -->
        <dependency>
            <groupId>com.dwarfeng</groupId>
            <artifactId>account-keeper-impl</artifactId>
        </dependency>
        <!-- Rbac-distributed-service 服务 -->
        <dependency>
            <groupId>com.dwarfeng</groupId>
            <artifactId>rbac-distributed-service-impl</artifactId>
        </dependency>
        <!-- Buddy 服务 -->
        <dependency>
            <groupId>com.dwarfeng</groupId>
            <artifactId>buddy-impl</artifactId>
        </dependency>
        <!-- SettingRepo 服务 -->
        <dependency>
            <groupId>com.dwarfeng</groupId>
            <artifactId>settingrepo-impl</artifactId>
        </dependency>
        <!-- Notify 服务 -->
        <dependency>
            <groupId>com.dwarfeng</groupId>
            <artifactId>notify-impl</artifactId>
        </dependency>
        <!-- 程序自身模块 -->
        <dependency>
            <groupId>com.dwarfeng</groupId>
            <artifactId>dwarfeng-essentials-sdk</artifactId>
        </dependency>
    </dependencies>
</project>
