# region acckeeper curator/latch-path.properties
# \u6E05\u7406\u670D\u52A1\u7684\u9886\u5BFC\u8005\u9501\u5B58\u7684\u8DEF\u5F84\u3002
com.dwarfeng.acckeeper.curator.latch_path.clean.leader_latch=/acckeeper/clean/leader_latch
# \u6E05\u9664\u670D\u52A1\u7684\u9886\u5BFC\u8005\u9501\u5B58\u7684\u8DEF\u5F84\u3002
com.dwarfeng.acckeeper.curator.latch_path.purge.leader_latch=/acckeeper/purge/leader_latch
# endregion
# region notify curator/latch-path.properties
# \u6E05\u9664\u670D\u52A1\u7684\u9886\u5BFC\u8005\u9501\u5B58\u7684\u8DEF\u5F84\u3002
com.dwarfeng.notify.curator.latch_path.purge.leader_latch=/acckeeper/purge/leader_latch
# endregion
# region logicengine curator/latch-path.properties
# \u4EFB\u52A1\u68C0\u67E5\u670D\u52A1\u7684\u9886\u5BFC\u8005\u9501\u8DEF\u5F84\u3002
com.dwarfeng.logicengine.curator.latch_path.task_check.leader_latch=/logic_engine/task_check/leader_latch
# \u4E3B\u7BA1\u670D\u52A1\u7684\u9886\u5BFC\u8005\u9501\u8DEF\u5F84\u3002
com.dwarfeng.logicengine.curator.latch_path.supervise.leader_latch=/logic_engine/supervise/leader_latch
# \u6E05\u9664\u670D\u52A1\u7684\u9886\u5BFC\u8005\u9501\u8DEF\u5F84\u3002
com.dwarfeng.logicengine.curator.latch_path.purge.leader_latch=/logic_engine/purge/leader_latch
# endregion
# region audit curator/latch-path.properties
# \u4EFB\u52A1\u68C0\u67E5\u670D\u52A1\u7684\u9886\u5BFC\u8005\u9501\u8DEF\u5F84\u3002
com.dwarfeng.audit.curator.latch_path.task_check.leader_latch=/audit/inspection_task_check/leader_latch
# \u81EA\u52A8\u5BA1\u8BA1\u4E3B\u7BA1\u670D\u52A1\u7684\u9886\u5BFC\u8005\u9501\u8DEF\u5F84\u3002
com.dwarfeng.audit.curator.latch_path.supervise.leader_latch=/audit/supervise/leader_latch
# \u6E05\u9664\u670D\u52A1\u7684\u9886\u5BFC\u8005\u9501\u8DEF\u5F84\u3002
com.dwarfeng.audit.curator.latch_path.purge.leader_latch=/audit/purge/leader_latch
# endregion
# region fileio curator/latch-path.properties
# \u9A71\u52A8\u670D\u52A1\u7684\u9886\u5BFC\u8005\u9501\u5B58\u7684\u8DEF\u5F84\u3002
com.dwarfeng.fileio.curator.latch_path.expire_check.leader_latch=/fileio/expire_check/leader_latch
# \u6E05\u9664\u5904\u7406\u5668\u7684\u9886\u5BFC\u8005\u9501\u5B58\u50A8\u7684\u8DEF\u5F84\u3002
com.dwarfeng.fileio.curator.latch_path.purge.leader_latch=/fileio/purge/leader_latch
# endregion
# region voucher curator/latch-path.properties
# \u6E05\u7406\u4F5C\u4E1A\u7684\u9886\u5BFC\u8005\u9501\u5B58\u7684\u8DEF\u5F84\u3002
com.dwarfeng.voucher.curator.latch_path.cleanup.leader_latch=/voucher/cleanup/leader_latch
# endregion
