# region acckeeper curator/latch-path.properties
# \u6E05\u7406\u670D\u52A1\u7684\u9886\u5BFC\u8005\u9501\u5B58\u7684\u8DEF\u5F84\u3002
com.dwarfeng.acckeeper.curator.latch_path.clean.leader_latch=/acckeeper/clean/leader_latch
# \u6E05\u9664\u670D\u52A1\u7684\u9886\u5BFC\u8005\u9501\u5B58\u7684\u8DEF\u5F84\u3002
com.dwarfeng.acckeeper.curator.latch_path.purge.leader_latch=/acckeeper/purge/leader_latch
# endregion acckeeper
# region notify curator/latch-path.properties
# \u6E05\u9664\u670D\u52A1\u7684\u9886\u5BFC\u8005\u9501\u5B58\u7684\u8DEF\u5F84\u3002
com.dwarfeng.notify.curator.latch_path.purge.leader_latch=/acckeeper/purge/leader_latch
# endregion notify
