# FTP \u6839\u8DEF\u5F84\u3002
#
#----------------------------------------Buddy----------------------------------------
com.dwarfeng.essentials.ftp.root_path.buddy=essentials/buddy
#
#----------------------------------------Settingrepo----------------------------------------
com.dwarfeng.essentials.ftp.root_path.settingrepo=essentials/settingrepo
