# region dubbo/connection.properties
com.dwarfeng.audit.dubbo.provider.group=${com.dwarfeng.essentials.dubbo.provider.audit.group}
# endregion
# region redis/prefix.properties
com.dwarfeng.audit.cache.prefix.entity.audit_category=\
  ${com.dwarfeng.essentials.cache.prefix.entity.audit.audit_category}
com.dwarfeng.audit.cache.prefix.entity.audit_property_indicator=\
  ${com.dwarfeng.essentials.cache.prefix.entity.audit.audit_property_indicator}
com.dwarfeng.audit.cache.prefix.entity.audit_entry=${com.dwarfeng.essentials.cache.prefix.entity.audit.audit_entry}
com.dwarfeng.audit.cache.prefix.entity.audit_entry_property=\
  ${com.dwarfeng.essentials.cache.prefix.entity.audit.audit_entry_property}
# endregion
# region redis/timeout.properties
com.dwarfeng.audit.cache.timeout.entity.audit_category=\
  ${com.dwarfeng.essentials.cache.timeout.entity.audit.audit_category}
com.dwarfeng.audit.cache.timeout.entity.audit_property_indicator=\
  ${com.dwarfeng.essentials.cache.timeout.entity.audit.audit_property_indicator}
com.dwarfeng.audit.cache.timeout.entity.audit_entry=${com.dwarfeng.essentials.cache.timeout.entity.audit.audit_entry}
com.dwarfeng.audit.cache.timeout.entity.audit_entry_property=\
  ${com.dwarfeng.essentials.cache.timeout.entity.audit.audit_entry_property}
# endregion
# region audit/audit-record.properties
com.dwarfeng.audit.audit_record.threshold.warn=${com.dwarfeng.essentials.audit.audit_record.threshold.warn}
com.dwarfeng.audit.audit_record.consumer_thread=${com.dwarfeng.essentials.audit.audit_record.consumer_thread}
com.dwarfeng.audit.audit_record.buffer_size=${com.dwarfeng.essentials.audit.audit_record.buffer_size}
# endregion
# region audit/consume.properties
com.dwarfeng.audit.consume.threshold.warn=${com.dwarfeng.essentials.audit.consume.threshold.warn}
com.dwarfeng.audit.consume.audit_record.consumer_thread=\
  ${com.dwarfeng.essentials.audit.consume.audit_record.consumer_thread}
com.dwarfeng.audit.consume.audit_record.buffer_size=${com.dwarfeng.essentials.audit.consume.audit_record.buffer_size}
com.dwarfeng.audit.consume.audit_record.batch_size=${com.dwarfeng.essentials.audit.consume.audit_record.batch_size}
com.dwarfeng.audit.consume.audit_record.max_idle_time=\
  ${com.dwarfeng.essentials.audit.consume.audit_record.max_idle_time}
com.dwarfeng.audit.consume.inspection_receive.consumer_thread=\
  ${com.dwarfeng.essentials.audit.consume.inspection_receive.consumer_thread}
com.dwarfeng.audit.consume.inspection_receive.buffer_size=\
  ${com.dwarfeng.essentials.audit.consume.inspection_receive.buffer_size}
com.dwarfeng.audit.consume.inspection_receive.batch_size=\
  ${com.dwarfeng.essentials.audit.consume.inspection_receive.batch_size}
com.dwarfeng.audit.consume.inspection_receive.max_idle_time=\
  ${com.dwarfeng.essentials.audit.consume.inspection_receive.max_idle_time}
# endregion
# region audit/inspection-dispatcher.properties
com.dwarfeng.audit.inspection_dispatcher.type=${com.dwarfeng.essentials.audit.inspection_dispatcher.type}
com.dwarfeng.audit.inspection_dispatcher.kafka.bootstrap_servers=\
  ${com.dwarfeng.essentials.audit.inspection_dispatcher.kafka.bootstrap_servers}
com.dwarfeng.audit.inspection_dispatcher.kafka.acks=${com.dwarfeng.essentials.audit.inspection_dispatcher.kafka.acks}
com.dwarfeng.audit.inspection_dispatcher.kafka.retries=\
  ${com.dwarfeng.essentials.audit.inspection_dispatcher.kafka.retries}
com.dwarfeng.audit.inspection_dispatcher.kafka.linger=\
  ${com.dwarfeng.essentials.audit.inspection_dispatcher.kafka.linger}
com.dwarfeng.audit.inspection_dispatcher.kafka.buffer_memory=\
  ${com.dwarfeng.essentials.audit.inspection_dispatcher.kafka.buffer_memory}
com.dwarfeng.audit.inspection_dispatcher.kafka.batch_size=\
  ${com.dwarfeng.essentials.audit.inspection_dispatcher.kafka.batch_size}
com.dwarfeng.audit.inspection_dispatcher.kafka.transaction_prefix=\
  ${com.dwarfeng.essentials.audit.inspection_dispatcher.kafka.transaction_prefix}
com.dwarfeng.audit.inspection_dispatcher.kafka.load_balance_mode=\
  ${com.dwarfeng.essentials.audit.inspection_dispatcher.kafka.load_balance_mode}
com.dwarfeng.audit.inspection_dispatcher.kafka.partition_check_interval=\
  ${com.dwarfeng.essentials.audit.inspection_dispatcher.kafka.partition_check_interval}
com.dwarfeng.audit.inspection_dispatcher.kafka.topic.dispatch=\
  ${com.dwarfeng.essentials.audit.inspection_dispatcher.kafka.topic.dispatch}
# endregion
# region audit/inspection-driver.properties
com.dwarfeng.audit.inspection_driver.kafka.dcti.bootstrap_servers=\
  ${com.dwarfeng.essentials.audit.inspection_driver.kafka.dcti.bootstrap_servers}
com.dwarfeng.audit.inspection_driver.kafka.dcti.session_timeout_ms=\
  ${com.dwarfeng.essentials.audit.inspection_driver.kafka.dcti.session_timeout_ms}
com.dwarfeng.audit.inspection_driver.kafka.dcti.auto_offset_reset=\
  ${com.dwarfeng.essentials.audit.inspection_driver.kafka.dcti.auto_offset_reset}
com.dwarfeng.audit.inspection_driver.kafka.dcti.concurrency=\
  ${com.dwarfeng.essentials.audit.inspection_driver.kafka.dcti.concurrency}
com.dwarfeng.audit.inspection_driver.kafka.dcti.poll_timeout=\
  ${com.dwarfeng.essentials.audit.inspection_driver.kafka.dcti.poll_timeout}
com.dwarfeng.audit.inspection_driver.kafka.dcti.listener_id=\
  ${com.dwarfeng.essentials.audit.inspection_driver.kafka.dcti.listener_id}
com.dwarfeng.audit.inspection_driver.kafka.dcti.listener_topic=\
  ${com.dwarfeng.essentials.audit.inspection_driver.kafka.dcti.listener_topic}
com.dwarfeng.audit.inspection_driver.kafka.dcti.max_poll_records=\
  ${com.dwarfeng.essentials.audit.inspection_driver.kafka.dcti.max_poll_records}
com.dwarfeng.audit.inspection_driver.kafka.dcti.max_poll_interval_ms=\
  ${com.dwarfeng.essentials.audit.inspection_driver.kafka.dcti.max_poll_interval_ms}
# endregion
# region audit/inspection-receiver.properties
com.dwarfeng.audit.inspection_receiver.type=${com.dwarfeng.essentials.audit.inspection_receiver.type}
com.dwarfeng.audit.inspection_receiver.kafka.bootstrap_servers=\
  ${com.dwarfeng.essentials.audit.inspection_receiver.kafka.bootstrap_servers}
com.dwarfeng.audit.inspection_receiver.kafka.session_timeout_ms=\
  ${com.dwarfeng.essentials.audit.inspection_receiver.kafka.session_timeout_ms}
com.dwarfeng.audit.inspection_receiver.kafka.auto_offset_reset=\
  ${com.dwarfeng.essentials.audit.inspection_receiver.kafka.auto_offset_reset}
com.dwarfeng.audit.inspection_receiver.kafka.concurrency=\
  ${com.dwarfeng.essentials.audit.inspection_receiver.kafka.concurrency}
com.dwarfeng.audit.inspection_receiver.kafka.poll_timeout=\
  ${com.dwarfeng.essentials.audit.inspection_receiver.kafka.poll_timeout}
com.dwarfeng.audit.inspection_receiver.kafka.listener_id=\
  ${com.dwarfeng.essentials.audit.inspection_receiver.kafka.listener_id}
com.dwarfeng.audit.inspection_receiver.kafka.listener_topic=\
  ${com.dwarfeng.essentials.audit.inspection_receiver.kafka.listener_topic}
com.dwarfeng.audit.inspection_receiver.kafka.max_poll_records=\
  ${com.dwarfeng.essentials.audit.inspection_receiver.kafka.max_poll_records}
com.dwarfeng.audit.inspection_receiver.kafka.max_poll_interval_ms=\
  ${com.dwarfeng.essentials.audit.inspection_receiver.kafka.max_poll_interval_ms}
com.dwarfeng.audit.inspection_receiver.dubbo.provider.group=\
  ${com.dwarfeng.essentials.audit.inspection_receiver.dubbo.provider.group}
# endregion
# region audit/inspection-task.properties
com.dwarfeng.audit.inspection_task.expire_timeout=${com.dwarfeng.essentials.audit.inspection_task.expire_timeout}
com.dwarfeng.audit.inspection_task.die_timeout=${com.dwarfeng.essentials.audit.inspection_task.die_timeout}
com.dwarfeng.audit.inspection_task.beat_interval=${com.dwarfeng.essentials.audit.inspection_task.beat_interval}
com.dwarfeng.audit.inspection_task.check.expire_check.cron=\
  ${com.dwarfeng.essentials.audit.inspection_task.check.expire_check.cron}
com.dwarfeng.audit.inspection_task.check.die_check.cron=\
  ${com.dwarfeng.essentials.audit.inspection_task.check.die_check.cron}
# endregion
# region audit/launcher.properties
com.dwarfeng.audit.launcher.reset_inspector_support=${com.dwarfeng.essentials.audit.launcher.reset_inspector_support}
com.dwarfeng.audit.launcher.reset_inspection_driver_support=\
  ${com.dwarfeng.essentials.audit.launcher.reset_inspection_driver_support}
com.dwarfeng.audit.launcher.start_audit_record_delay=\
  ${com.dwarfeng.essentials.audit.launcher.start_audit_record_delay}
com.dwarfeng.audit.launcher.start_reset_delay=${com.dwarfeng.essentials.audit.launcher.start_reset_delay}
com.dwarfeng.audit.launcher.online_inspection_task_check_delay=\
  ${com.dwarfeng.essentials.audit.launcher.online_inspection_task_check_delay}
com.dwarfeng.audit.launcher.enable_inspection_task_check_delay=\
  ${com.dwarfeng.essentials.audit.launcher.enable_inspection_task_check_delay}
com.dwarfeng.audit.launcher.start_inspection_receiver_delay=\
  ${com.dwarfeng.essentials.audit.launcher.start_inspection_receiver_delay}
com.dwarfeng.audit.launcher.online_inspection_supervise_delay=\
  ${com.dwarfeng.essentials.audit.launcher.online_inspection_supervise_delay}
com.dwarfeng.audit.launcher.enable_inspection_supervise_delay=\
  ${com.dwarfeng.essentials.audit.launcher.enable_inspection_supervise_delay}
com.dwarfeng.audit.launcher.online_purge_delay=${com.dwarfeng.essentials.audit.launcher.online_purge_delay}
com.dwarfeng.audit.launcher.enable_purge_delay=${com.dwarfeng.essentials.audit.launcher.enable_purge_delay}
# endregion
# region audit/purge.properties
com.dwarfeng.audit.purge.retention_duration=${com.dwarfeng.essentials.audit.purge.retention_duration}
com.dwarfeng.audit.purge.task_cron=${com.dwarfeng.essentials.audit.purge.task_cron}
com.dwarfeng.audit.purge.max_page_size=${com.dwarfeng.essentials.audit.purge.max_page_size}
com.dwarfeng.audit.purge.max_deletion_size=${com.dwarfeng.essentials.audit.purge.max_deletion_size}
# endregion
# region audit/push.properties
com.dwarfeng.audit.pusher.type=${com.dwarfeng.essentials.audit.pusher.type}
com.dwarfeng.audit.pusher.multi.delegate_types=${com.dwarfeng.essentials.audit.pusher.multi.delegate_types}
com.dwarfeng.audit.pusher.kafka.native.bootstrap_servers=\
  ${com.dwarfeng.essentials.audit.pusher.kafka.native.bootstrap_servers}
com.dwarfeng.audit.pusher.kafka.native.acks=${com.dwarfeng.essentials.audit.pusher.kafka.native.acks}
com.dwarfeng.audit.pusher.kafka.native.retries=${com.dwarfeng.essentials.audit.pusher.kafka.native.retries}
com.dwarfeng.audit.pusher.kafka.native.linger=${com.dwarfeng.essentials.audit.pusher.kafka.native.linger}
com.dwarfeng.audit.pusher.kafka.native.buffer_memory=\
  ${com.dwarfeng.essentials.audit.pusher.kafka.native.buffer_memory}
com.dwarfeng.audit.pusher.kafka.native.batch_size=${com.dwarfeng.essentials.audit.pusher.kafka.native.batch_size}
com.dwarfeng.audit.pusher.kafka.native.transaction_prefix=\
  ${com.dwarfeng.essentials.audit.pusher.kafka.native.transaction_prefix}
com.dwarfeng.audit.pusher.kafka.native.topic.audit_record_reset=\
  ${com.dwarfeng.essentials.audit.pusher.kafka.native.topic.audit_record_reset}
com.dwarfeng.audit.pusher.kafka.native.topic.inspection_supervise_reset=\
  ${com.dwarfeng.essentials.audit.pusher.kafka.native.topic.inspection_supervise_reset}
com.dwarfeng.audit.pusher.kafka.native.topic.inspection_task_finished=\
  ${com.dwarfeng.essentials.audit.pusher.kafka.native.topic.inspection_task_finished}
com.dwarfeng.audit.pusher.kafka.native.topic.inspection_task_failed=\
  ${com.dwarfeng.essentials.audit.pusher.kafka.native.topic.inspection_task_failed}
com.dwarfeng.audit.pusher.kafka.native.topic.inspection_task_expired=\
  ${com.dwarfeng.essentials.audit.pusher.kafka.native.topic.inspection_task_expired}
com.dwarfeng.audit.pusher.kafka.native.topic.inspection_task_died=\
  ${com.dwarfeng.essentials.audit.pusher.kafka.native.topic.inspection_task_died}
com.dwarfeng.audit.pusher.kafka.native.topic.inspection_job_reset=\
  ${com.dwarfeng.essentials.audit.pusher.kafka.native.topic.inspection_job_reset}
com.dwarfeng.audit.pusher.kafka.native.topic.inspection_alarm_created=\
  ${com.dwarfeng.essentials.audit.pusher.kafka.native.topic.inspection_alarm_created}
com.dwarfeng.audit.pusher.kafka.native.topic.purge_finished=\
  ${com.dwarfeng.essentials.audit.pusher.kafka.native.topic.purge_finished}
com.dwarfeng.audit.pusher.kafka.native.topic.purge_failed=\
  ${com.dwarfeng.essentials.audit.pusher.kafka.native.topic.purge_failed}
com.dwarfeng.audit.pusher.log.log_level=${com.dwarfeng.essentials.audit.pusher.log.log_level}
# endregion
# region audit/reset.properties
com.dwarfeng.audit.resetter.fixed_delay.delay=${com.dwarfeng.essentials.audit.resetter.fixed_delay.delay}
com.dwarfeng.audit.resetter.fixed_rate.rate=${com.dwarfeng.essentials.audit.resetter.fixed_rate.rate}
com.dwarfeng.audit.resetter.cron.cron=${com.dwarfeng.essentials.audit.resetter.cron.cron}
# endregion
