#------------------------------------------------------------------------------------
# \u7F13\u5B58\u952E\u524D\u7F00\u914D\u7F6E\u3002
#------------------------------------------------------------------------------------
# \u5BA1\u8BA1\u7C7B\u522B\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.audit.audit_category=com.dwarfeng.audit.entity.audit_category.
# \u5BA1\u8BA1\u5C5E\u6027\u6307\u793A\u5668\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.audit.audit_property_indicator=\
  com.dwarfeng.audit.entity.audit_property_indicator.
# \u5BA1\u8BA1\u6761\u76EE\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.audit.audit_entry=com.dwarfeng.audit.entity.audit_entry.
# \u5BA1\u8BA1\u6761\u76EE\u5C5E\u6027\u7684\u4E3B\u952E\u683C\u5F0F\u3002
com.dwarfeng.essentials.cache.prefix.entity.audit.audit_entry_property=\
  com.dwarfeng.audit.entity.audit_entry_property.
# \u81EA\u52A8\u5BA1\u8BA1\u62A5\u8B66\u7C7B\u578B\u6307\u793A\u5668\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.inspection_alarm_type_indicator=entity.inspection_alarm_type_indicator.
# \u81EA\u52A8\u5BA1\u8BA1\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.inspection=entity.inspection.
# \u81EA\u52A8\u5BA1\u8BA1\u62A5\u8B66\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.inspection_alarm=entity.inspection_alarm.
# \u81EA\u52A8\u5BA1\u8BA1\u9A71\u52A8\u5668\u4FE1\u606F\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.inspection_driver_info=entity.inspection_driver_info.
# \u81EA\u52A8\u5BA1\u8BA1\u9A71\u52A8\u5668\u652F\u6301\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.inspection_driver_support=entity.inspection_driver_support.
# \u81EA\u52A8\u5BA1\u8BA1\u4EFB\u52A1\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.inspection_task=entity.inspection_task.
# \u81EA\u52A8\u5BA1\u8BA1\u4EFB\u52A1\u4E8B\u4EF6\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.inspection_task_event=entity.inspection_task_event.
# \u5BA1\u8BA1\u5668\u4FE1\u606F\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.inspector_info=entity.inspector_info.
# \u5BA1\u8BA1\u5668\u652F\u6301\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.inspector_support=entity.inspector_support.
# \u5BA1\u8BA1\u5668\u53D8\u91CF\u7684\u4E3B\u952E\u683C\u5F0F\u3002
cache.prefix.entity.inspector_variable=entity.inspector_variable.
